### ISSUE TITLE
Error When spawning mediasoup worker

### ISSUE THREAD

**Issue by ratatatatat** [mkhahani/mediasoup-sample-app#4]
I tried running the demo on an EC2 instance running ubuntu 18.04. 
I get the following error.

{ Error: spawn /home/ubuntu/mediasoup-sample-app/node_modules/mediasoup/worker/out/Release/mediasoup-worker ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /home/ubuntu/mediasoup-sample-app/node_modules/mediasoup/worker/out/Release/mediasoup-worker',
  path: '/home/ubuntu/mediasoup-sample-app/node_modules/mediasoup/worker/out/Release/mediasoup-worker',
  spawnargs:
   [ '--logLevel=warn',
     '--logTag=info',
     '--logTag=ice',
     '--logTag=dtls',
     '--logTag=rtp',
     '--logTag=srtp',
     '--logTag=rtcp',
     '--rtcMinPort=10000',
     '--rtcMaxPort=10100' ] }

I'm not sure if mediasoup installed/built properly. 

Also using node v8.10

Any help is appreciated

**Comment by ratatatatat** [comment]
I think this is an issue with the build process during mediasoup installation.

**Comment by puwnautladplee** [comment]
@ratatatatat 
how do you fix ?
