### ISSUE TITLE
"mediasoup.createWorker is not a function" on startup

### ISSUE THREAD

**Issue by FlisherOfatale** [mkhahani/mediasoup-sample-app#8]
Hi,

I'm getting the following error message when launching the server.
I'm running node v12.11.1 on Ubuntu 18.04.
browserify is installed as global

(replaced 2 digit in the up by XX)
the listenIp is still 0.0.0.0 but I had no better result by inserting the real ip
The listing IP at the end of the config was the real one.

The server remain up but crash when a client connect.
Here is my  log from the console.

Sidenote: the open https// is missing the ":", which isn't important I guess.

```log
> root@ubuntu-s-1vcpu-1gb-tor1-01:/opt/m/mediasoup-sample-app# npm start
> 
> > mediasoup-sample-app@1.2.0 start /opt/m/mediasoup-sample-app
> > browserify client.js -o app-bundle.js; node server.js
> 
> server is running
> open https//159.203.XX.XX:3000 in your web browser
> TypeError: mediasoup.createWorker is not a function
>     at runMediasoupWorker (/opt/m/mediasoup-sample-app/server.js:156:28)
>     at /opt/m/mediasoup-sample-app/server.js:24:11
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> client connected
> /opt/m/mediasoup-sample-app/server.js:100
>       callback(mediasoupRouter.rtpCapabilities);
>                                ^
> 
> TypeError: Cannot read property 'rtpCapabilities' of undefined
>     at Socket.<anonymous> (/opt/m/mediasoup-sample-app/server.js:100:32)
>     at Socket.emit (events.js:210:5)
>     at /opt/m/mediasoup-sample-app/node_modules/socket.io/lib/socket.js:528:12
>     at processTicksAndRejections (internal/process/task_queues.js:75:11)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! mediasoup-sample-app@1.2.0 start: `browserify client.js -o app-bundle.js; node server.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the mediasoup-sample-app@1.2.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2019-10-14T14_36_13_169Z-debug.log
> ```

**Comment by FlisherOfatale** [comment]
Got fixed after I manually compiled from /node_module/mediaserver/worker using 
```PYTHON=python3 npm install mediasoup@3 --save```
